before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - id: mcl
    main: ./cmd/mcl
    binary: mcl
    flags:
      - -v
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
    ldflags:
      - "{{ if not .IsSnapshot }}-s -w{{ end }}"
      - -X github.com/snugfox/mcl/pkg/version.BuildDate="{{ .Date }}"
      - -X github.com/snugfox/mcl/pkg/version.GoVersion="{{ .Env.GOVER }}"
      - -X github.com/snugfox/mcl/pkg/version.Revision="{{ .ShortCommit }}"
      - -X github.com/snugfox/mcl/pkg/version.Version="{{ .Version }}"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
release:
  github:
    owner: snugfox
    name: mcl
  prerelease: auto
changelog:
  skip: true
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - snugfox/mcl:{{ .Tag }}
      - snugfox/mcl:v{{ .Major }}.{{ .Minor }}
      - docker.pkg.github.com/snugfox/mcl/mcl:{{ .Tag }}
      - docker.pkg.github.com/snugfox/mcl/mcl:v{{ .Major }}.{{ .Minor }}
    dockerfile: build/Dockerfile
