before:
  hooks:
    - go mod download
builds:
  - id: mcl
    main: ./cmd/mcl
    binary: mcl
    flags:
      - -v
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
release:
  github:
    owner: snugfox
    name: mcl
  prerelease: auto
changelog:
  skip: true
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - snugfox/mcl:latest
      - snugfox/mcl:{{ .Tag }}
    dockerfile: build/Dockerfile
