before:
  hooks:
    - go generate ./...
    - go mod download
builds:
  - id: mcl
    main: ./cmd/mcl
    binary: mcl
    flags:
      - -v
      - -trimpath
      - -mod=readonly
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - 386
      - arm64
      - arm
      - ppc64le
    goarm:
      - 7
      - 6
      - 5
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: freebsd
        goarch: arm64
    ldflags:
      - "{{ if not .IsSnapshot }}-s -w{{ end }}"
      - -X github.com/snugfox/mcl/pkg/version.BuildDate="{{ .Date }}"
      - -X github.com/snugfox/mcl/pkg/version.GoVersion="{{ .Env.GOVER }}"
      - -X github.com/snugfox/mcl/pkg/version.Revision="{{ .ShortCommit }}"
      - -X github.com/snugfox/mcl/pkg/version.Version="{{ .Version }}"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
release:
  github:
    owner: snugfox
    name: mcl
  prerelease: auto
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^doc:'
      - 'typo'
dockers:
  - goos: linux
    goarch: amd64
    binaries: [mcl]
    image_templates:
      - snugfox/mcl:{{ .Tag }}
      - snugfox/mcl:v{{ .Major }}.{{ .Minor }}
    dockerfile: build/deploy/Dockerfile
  - goos: linux
    goarch: amd64
    binaries: [mcl]
    image_templates:
      - snugfox/mcl:{{ .Tag }}-java8
      - snugfox/mcl:v{{ .Major }}.{{ .Minor }}-java8
    dockerfile: build/deploy/Dockerfile.java8
  - goos: linux
    goarch: amd64
    binaries: [mcl]
    image_templates:
      - snugfox/mcl:{{ .Tag }}-java11
      - snugfox/mcl:v{{ .Major }}.{{ .Minor }}-java11
    dockerfile: build/deploy/Dockerfile.java11
  - goos: linux
    goarch: amd64
    binaries: [mcl]
    image_templates:
      - snugfox/mcl:{{ .Tag }}-java14
      - snugfox/mcl:v{{ .Major }}.{{ .Minor }}-java14
    dockerfile: build/deploy/Dockerfile.java14
