name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run tests
    needs: [builder]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull builder
        run: ./build/builder.sh
      - name: Run tests
        run: ./build/builder.sh run make test

  build-snapshot:
    name: Build snapshot
    needs: [builder]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Pull builder
        run: ./build/builder.sh
      - name: Build
        run: ./build/builder.sh run make build-snapshot
